override_dh_auto_clean: unprepared
	rm -f $(subst @PHP_VERSION@,$(PHP_NAME_VERSION),$(PREPARE_FILES))

	rm -rf test-results.txt

	# clean up autogenerated cruft
	cat debian/modulelist | while read module extname dsoname priority; do \
	    $(MODULE_PACKAGE) \
	    for cruft in postinst preinst prerm postrm; do \
	        rm -f debian/$${package}.$${cruft}; \
	    done; \
	done

	extdir=`debian/tmp/usr/bin/php-config$(PHP_NAME_VERSION) --extension-dir | cut -b2- `; \
	for sapi in $(REAL_TARGETS); do \
		$(SAPI_PACKAGE) \
		for cruft in preinst postinst prerm postrm links dirs triggers lintian-overrides; do \
			rm -f debian/$${package}.$${cruft}; \
		done; \
	done

	# clean build directories
	for target in $(TARGETS); do \
	  dh_auto_clean --builddirectory $${target}-build $(PARALLEL); \
	  rm -rf $${target}-build; \
	done

	# remove shared config.cache
	rm -f $(CURDIR)/config.cache
