name: 'Refresh PHP development containers'

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rebuild:
    name: Build
    uses: ./.github/workflows/build-images.yml
    with:
      push: true
    secrets: inherit
