name: 'PR changed'

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rebuild:
    name: Build
    uses: ./.github/workflows/build-images.yml
    secrets: inherit
